### ISSUE TITLE
自动生成的sys_casbin_rule能否设置前缀

### ISSUE THREAD

**Issue by qiuyier** [jxo-me/gdb-adapter#1]
如题所问，在没有sys_casbin_rule这张表时初始化会自动生成这张表，但是我在数据库的配置里面prefix定义了a_这种前缀。因此会导致数据库报错找不到a_sys_casbin_rule这张表。当我手动在数据库加上这个前缀后，再次启动会再次生成一张sys_casbin_rule表，导致冗余，请问能否在生成表时添加前缀呢

**Comment by jxo-me** [comment]
最新版本v1.0.2已经支持prefix生成表前缀
